// The engine's mode roster and the anchors' family constants, baked from the
// wallpaper project at build time.
//
// Generated by `python -m builder explorer` — edit that, not this. What a
// permalink will ACCEPT is not here: `permalink.js` keeps its own vocabulary, so
// that rebuilding this file can never widen the contract. What is here is what
// those names mean — the line under each mode in the picker, and the constant a
// dynamical plane opens at.

export const PROVENANCE = {
  "baked": "2026-08-21",
  "constants_from": "data/anchors.jsonl",
  "modes_from": "fractal-engine modes",
  "wallpapers_commit": "f275e13687532f8bd0b15f268c31077dbe917048"
};

export const MODES = new Map([
  ["smooth", "Fractional escape time: the spine every composite builds on."],
  ["tia", "Triangle-inequality average: fine engraved banding."],
  ["stripe", "Stripe average at density 6: combed flowing striations."],
  ["exp_smoothing", "Sum of exp(-|z|) over the orbit: an averaging alternative to smooth."],
  ["gaussian_int", "Closest approach to the integer lattice: a tiled, beaded field."],
  ["trap_circle", "Closest approach to the unit circle, read through a log curve."],
  ["curvature", "Mean turning angle of the orbit."],
  ["smooth_mean_angle", "Smooth base, screened with the lattice trap's spread angle."],
  ["smooth_angle_min", "Smooth base, screened with the angle at the lattice's closest approach."],
  ["smooth_trap_circle", "Smooth base, screened with the circle trap: structure in the interior."],
  ["smooth_stripe", "Smooth base, screened with the stripe average."],
  ["smooth_curvature", "Smooth base, screened with curvature."],
  ["direct_trap_ring", "Direct trap, ring shape, screened over black: the cleanest of the family."],
  ["direct_trap_screen", "Direct trap, cross shape, screened over black: bright thorns."],
  ["direct_trap_multiply", "Direct trap, cross shape, multiplied over white: dark lace on light."],
  ["direct_trap_lines", "Direct trap on the real axis: the narrowest, most directional member."],
  ["threads", "Smooth base plus the accumulated cross trap: sparse organic flow."],
  ["itinerary", "Smooth base whose palette position the orbit's angular address shifts. The address opens at z1 on a dynamical plane and at z0 on a parameter one."],
]);

export const CONSTANTS = {
  "julia": {
    "cx": "-0.07810228973371881",
    "cy": "-0.6514609012382414"
  },
  "julia3": {
    "cx": "-0.07810228973371881",
    "cy": "-0.6514609012382414"
  },
  "julia4": {
    "cx": "-0.07810228973371881",
    "cy": "-0.6514609012382414"
  },
  "julia5": {
    "cx": "-0.07810228973371881",
    "cy": "-0.6514609012382414"
  },
  "phoenix": {
    "cx": "0.5667",
    "cy": "0",
    "px": "-0.5",
    "py": "0",
    "zx": "0",
    "zy": "0"
  }
};

export const CURVES = {
  "curvature": "linear",
  "direct_trap_lines": "linear",
  "direct_trap_multiply": "linear",
  "direct_trap_ring": "linear",
  "direct_trap_screen": "linear",
  "exp_smoothing": "linear",
  "gaussian_int": "linear",
  "itinerary": "linear",
  "smooth": "linear",
  "smooth_angle_min": "linear",
  "smooth_curvature": "linear",
  "smooth_mean_angle": "linear",
  "smooth_stripe": "linear",
  "smooth_trap_circle": "linear",
  "stripe": "linear",
  "threads": "linear",
  "tia": "linear",
  "trap_circle": "log"
};
