"""Generating the gallery pages.

Every page here is a pure function of the metadata files: same text in, same bytes out.
Nothing is read off an image, nothing is stamped with a date, and the only ordering is
the one the metadata gives. That is what makes `check`'s regenerate-and-compare a real
check rather than a coin toss.
"""

from . import figures, links
from . import sections as sections_module
from .escape import attribute, text
from .galleries import Gallery
from .paths import GALLERIES_DIR, SITE_ROOT, relative_href

GENERATED_NOTICE = (
    "<!-- Generated by builder/. Do not edit by hand — run `python -m builder build`. -->"
)

SITE_TITLE = "Making Fractal Wallpapers"
CODE_REPO = "https://github.com/techmatt/fractal-wallpapers"
AUTHOR_SITE = "https://techmatt.github.io/"

FOOTER = f"""<footer>
  <p><a href="{AUTHOR_SITE}">Matt Fisher</a>
  · <a href="{CODE_REPO}">fractal-wallpapers</a> · MIT</p>
</footer>"""


def index_path() -> str:
    return "index.html"


def gallery_page_path(gallery: Gallery):
    return GALLERIES_DIR / f"{gallery.slug}.html"


def topbar(home: str, galleries_index: str) -> str:
    """The site bar every page carries: back to the front page, out to the code and
    to the author's homepage — this site is one project of several living under it.

    Both hrefs are passed in already relative to the page that will hold them — the
    bar is the same line everywhere, and only its depth differs.
    """
    return "\n".join(
        [
            '<nav class="topbar">',
            '  <div class="topbar-inner">',
            f'    <a class="topbar-site" href="{attribute(home)}">{text(SITE_TITLE)}</a>',
            '    <span class="topbar-links"><a href="'
            f'{attribute(galleries_index)}">Galleries</a><a href="{CODE_REPO}">GitHub</a>'
            f'<a href="{AUTHOR_SITE}">Matt Fisher</a></span>',
            "  </div>",
            "</nav>",
        ]
    )


def _shell(*, title: str, css: str, bar: str, rail: str, header: str, blocks: list[str]) -> str:
    """The shape every page has: the site bar, the contents rail, the column beside it.

    A gallery is not an article section, so no entry in the rail is the current one
    here — on these pages the rail is the way back into the article.
    """
    body = "\n\n".join(blocks)
    return (
        "\n".join(
            [
                "<!doctype html>",
                '<html lang="en">',
                "<head>",
                GENERATED_NOTICE,
                '<meta charset="utf-8">',
                '<meta name="viewport" content="width=device-width, initial-scale=1">',
                f"<title>{text(title)}</title>",
                f'<link rel="stylesheet" href="{css}">',
                "</head>",
                "<body>",
                bar,
                "",
                '<div class="page">',
                rail,
                "",
                '<div class="page-body">',
                header,
                "",
                "<main>",
                body,
                "</main>",
                "",
                FOOTER,
                "</div>",
                "</div>",
                "</body>",
                "</html>",
            ]
        )
        + "\n"
    )


def _masthead(kicker: str | None, heading: str) -> str:
    """The page's own title block: a kicker where one earns its place, and the title.

    Nothing else. Site branding lives in the bar above it, so a page whose kicker would
    only have repeated the site title carries no kicker at all — and no page here carries
    a standfirst, because the ruling in `writing-guidance.md` cut the device site-wide.
    A gallery opens on its lead like every other page, and the sentence that used to sit
    under the title is the first sentence of that lead.
    """
    lines = ['<header class="masthead">']
    if kicker:
        lines.append(f'  <p class="kicker">{kicker}</p>')
    lines.extend([f"  <h1>{text(heading)}</h1>", "</header>"])
    return "\n".join(lines)


def _tile(*, link: str, src: str, size: tuple[int, int], alt: str, caption: str) -> list[str]:
    width, height = size
    return [
        '      <figure class="tile">',
        f'        <a href="{attribute(link)}">',
        f'          <img src="{attribute(src)}" width="{width}" height="{height}" '
        f'alt="{attribute(alt)}" loading="lazy">',
        "        </a>",
        f"        <figcaption>{caption}</figcaption>",
        "      </figure>",
    ]


def _grid(tiles: list[list[str]]) -> str:
    lines = ['  <section class="images">', '    <div class="grid">']
    for tile in tiles:
        lines.extend(tile)
    lines.extend(["    </div>", "  </section>"])
    return "\n".join(lines)


def _count(images: int) -> str:
    return "1 image" if images == 1 else f"{images} images"


def gallery_page(gallery: Gallery, sections: list[sections_module.Section]) -> str:
    """The HTML for one gallery."""
    page = gallery_page_path(gallery)
    css = relative_href(page, SITE_ROOT / "assets" / "css" / "site.css")
    article = relative_href(page, SITE_ROOT / "index.html")

    header = _masthead(f'<a href="{index_path()}">Galleries</a>', gallery.title)

    intro = ['  <section class="intro">', f"    <p>{text(gallery.blurb)}</p>"]
    if gallery.note:
        intro.append(f"    <p>{text(gallery.note)}</p>")
    if gallery.release:
        intro.append(
            f'    <p>Full size: <a href="{attribute(gallery.release)}">release downloads</a>.</p>'
        )
    intro.append(f'    <p><a href="{index_path()}">All galleries</a></p>')
    intro.append("  </section>")

    reopened = links.opened(page)
    tiles = []
    for image in gallery.images:
        web_res = gallery.directory / image.file
        thumb = gallery.thumbs_directory / image.file
        caption = f"<strong>{text(image.title)}</strong> — {text(image.caption)}"
        if image.credit:
            caption += f' <span class="credit">{text(image.credit)}</span>'
        opened = reopened.get(f"gallery:{gallery.slug}/{image.file}")
        if opened:
            caption += f' <a class="open" href="{attribute(opened)}">{figures.OPEN_TEXT}</a>'
        tiles.append(
            _tile(
                link=relative_href(page, web_res),
                src=relative_href(page, thumb),
                size=image.thumb_size,
                alt=image.alt,
                caption=caption,
            )
        )

    return _shell(
        title=f"{gallery.title} — Making Fractal Wallpapers",
        css=css,
        bar=topbar(article, index_path()),
        rail=sections_module.block(page, sections),
        header=header,
        blocks=["\n".join(intro), _grid(tiles)],
    )


def gallery_index(galleries: list[Gallery], sections: list[sections_module.Section]) -> str:
    """The HTML for the gallery index: one cover tile per gallery."""
    page = GALLERIES_DIR / "index.html"
    css = relative_href(page, SITE_ROOT / "assets" / "css" / "site.css")
    article = relative_href(page, SITE_ROOT / "index.html")

    header = _masthead(None, "Galleries")

    intro = ['  <section class="intro">']
    if galleries:
        intro.append(
            "    <p>Images on these pages are web-res. Anything a reader would want at "
            "full size is a release download.</p>"
        )
    else:
        intro.append("    <p>No galleries have been built yet.</p>")
    intro.append(f'    <p><a href="{attribute(article)}">Back to the article</a></p>')
    intro.append("  </section>")

    blocks = ["\n".join(intro)]
    if galleries:
        tiles = []
        for gallery in galleries:
            cover = gallery.images[0]
            link = f"{gallery.slug}.html"
            caption = (
                f'<strong><a href="{link}">{text(gallery.title)}</a></strong> — '
                f"{text(gallery.blurb)} "
                f'<span class="credit">{_count(len(gallery.images))}</span>'
            )
            tiles.append(
                _tile(
                    link=link,
                    src=relative_href(page, gallery.thumbs_directory / cover.file),
                    size=cover.thumb_size,
                    alt=cover.alt,
                    caption=caption,
                )
            )
        blocks.append(_grid(tiles))

    return _shell(
        title="Galleries — Making Fractal Wallpapers",
        css=css,
        bar=topbar(article, index_path()),
        rail=sections_module.block(page, sections),
        header=header,
        blocks=blocks,
    )


def generated_pages(galleries: list[Gallery], sections: list[sections_module.Section]) -> dict:
    """Every page the builder owns, as {path: html}. The set `check` compares against."""
    pages = {GALLERIES_DIR / "index.html": gallery_index(galleries, sections)}
    for gallery in galleries:
        pages[gallery_page_path(gallery)] = gallery_page(gallery, sections)
    return pages
