"""Generating the gallery pages.

Every page here is a pure function of the metadata files: same text in, same bytes out.
Nothing is read off an image, nothing is stamped with a date, and the only ordering is
the one the metadata gives. That is what makes `check`'s regenerate-and-compare a real
check rather than a coin toss.
"""

from pathlib import Path

from . import figures, icons, links
from . import palettes as palettes_module
from . import sections as sections_module
from .escape import attribute, text
from .galleries import Gallery
from .paths import GALLERIES_DIR, SITE_ROOT, relative_href

#: What a block's lines are joined with. Named because these pages are assembled inside
#: f-strings, and a bare escape inside one is a character nobody can see in a diff.
NEWLINE = "\n"

GENERATED_NOTICE = (
    "<!-- Generated by builder/. Do not edit by hand — run `python -m builder build`. -->"
)

SITE_TITLE = "Making Fractal Wallpapers"

#: The pipeline's code — the project this article is about. Named wherever the article
#: talks about how the pictures were made, and in the footer.
CODE_REPO = "https://github.com/techmatt/fractal-wallpapers"

#: This site's own code *(figure_split_overview_ckpt140, 2026-09-22)*. The bar's `GitHub`
#: used to point next door, which is the one link on the page a reader cannot guess wrong:
#: a bar link named after the site is the site, and somebody who wanted to see how a page
#: they were reading is built landed in a renderer instead. The pipeline is still one click
#: away — the contents rail carries it, the footer carries it, and the article names it
#: wherever it talks about the code that drew the pictures.
SITE_REPO = "https://github.com/techmatt/fractals"

AUTHOR_SITE = "https://techmatt.github.io/"

#: Where the committed tree is served. The site itself never spells it — every href is
#: relative — and it exists for what leaves the site: a review doc's links resolve here.
SITE_URL = "https://techmatt.github.io/fractals/"

FOOTER = f"""<footer>
  <p><a href="{AUTHOR_SITE}">Matt Fisher</a>
  · <a href="{CODE_REPO}">fractal-wallpapers</a> · MIT</p>
</footer>"""


def index_path() -> str:
    return "index.html"


def gallery_page_path(gallery: Gallery):
    return GALLERIES_DIR / f"{gallery.slug}.html"


def topbar(home: str, galleries_index: str) -> str:
    """The site bar every page carries: back to the front page, out to this site's own
    source and to the author's homepage — this site is one project of several living
    under it.

    Both hrefs are passed in already relative to the page that will hold them — the
    bar is the same line everywhere, and only its depth differs.
    """
    return "\n".join(
        [
            '<nav class="topbar">',
            '  <div class="topbar-inner">',
            f'    <a class="topbar-site" href="{attribute(home)}">{text(SITE_TITLE)}</a>',
            '    <span class="topbar-links"><a href="'
            f'{attribute(galleries_index)}">Wallpaper packs</a><a href="{SITE_REPO}">GitHub</a>'
            f'<a href="{AUTHOR_SITE}">Matt Fisher</a></span>',
            "  </div>",
            "</nav>",
        ]
    )


def _shell(
    *, page: Path, title: str, css: str, bar: str, rail: str, header: str, blocks: list[str]
) -> str:
    """The shape every page has: the site bar, the contents rail, the column beside it.

    A gallery is not an article section, so no entry in the rail is the current one
    here — on these pages the rail is the way back into the article.
    """
    body = "\n\n".join(blocks)
    return (
        "\n".join(
            [
                "<!doctype html>",
                '<html lang="en">',
                "<head>",
                GENERATED_NOTICE,
                '<meta charset="utf-8">',
                '<meta name="viewport" content="width=device-width, initial-scale=1">',
                # **The site's icon, declared on every page** *(favicon_wire_ckpt145)*. A
                # browser asks every origin for `/favicon.ico` unbidden, and under a
                # project-Pages subpath this site cannot answer at the origin root, so a page
                # that declares nothing logs a 404. `builder.icons` owns the lines and spells
                # them from the page; the hand-written pages get the same lines from `build`.
                icons.head(page),
                f"<title>{text(title)}</title>",
                f'<link rel="stylesheet" href="{css}">',
                "</head>",
                "<body>",
                bar,
                "",
                '<div class="page">',
                rail,
                "",
                '<div class="page-body">',
                header,
                "",
                "<main>",
                body,
                "</main>",
                "",
                FOOTER,
                "</div>",
                "</div>",
                "</body>",
                "</html>",
            ]
        )
        + "\n"
    )


def _masthead(kicker: str | None, heading: str) -> str:
    """The page's own title block: a kicker where one earns its place, and the title.

    Nothing else. Site branding lives in the bar above it, so a page whose kicker would
    only have repeated the site title carries no kicker at all — and no page here carries
    a standfirst, because the ruling in `writing-guidance.md` cut the device site-wide.
    A gallery opens on its lead like every other page, and the sentence that used to sit
    under the title is the first sentence of that lead.
    """
    lines = ['<header class="masthead">']
    if kicker:
        lines.append(f'  <p class="kicker">{kicker}</p>')
    lines.extend([f"  <h1>{text(heading)}</h1>", "</header>"])
    return "\n".join(lines)


def _tile(*, link: str, src: str, size: tuple[int, int], alt: str, caption: str) -> list[str]:
    width, height = size
    return [
        '      <figure class="tile">',
        f'        <a href="{attribute(link)}">',
        f'          <img src="{attribute(src)}" width="{width}" height="{height}" '
        f'alt="{attribute(alt)}" loading="lazy">',
        "        </a>",
        f"        <figcaption>{caption}</figcaption>",
        "      </figure>",
    ]


def _grid(tiles: list[list[str]]) -> str:
    lines = ['  <section class="images">', '    <div class="grid">']
    for tile in tiles:
        lines.extend(tile)
    lines.extend(["    </div>", "  </section>"])
    return "\n".join(lines)


def _count(images: int) -> str:
    return "1 image" if images == 1 else f"{images} images"


def gallery_page(gallery: Gallery, sections: list[sections_module.Section]) -> str:
    """The HTML for one gallery."""
    page = gallery_page_path(gallery)
    css = relative_href(page, SITE_ROOT / "assets" / "css" / "site.css")
    article = relative_href(page, SITE_ROOT / "index.html")

    header = _masthead(f'<a href="{index_path()}">Wallpaper packs</a>', gallery.title)

    intro = ['  <section class="intro">', f"    <p>{text(gallery.blurb)}</p>"]
    if gallery.note:
        intro.append(f"    <p>{text(gallery.note)}</p>")
    if gallery.release:
        intro.append(
            f'    <p>Full size: <a href="{attribute(gallery.release)}">release downloads</a>.</p>'
        )
    intro.append(f'    <p><a href="{index_path()}">All wallpaper packs</a></p>')
    intro.append("  </section>")

    reopened = links.opened(page)
    tiles = []
    for image in gallery.images:
        web_res = gallery.directory / image.file
        thumb = gallery.thumbs_directory / image.file
        caption = f"<strong>{text(image.title)}</strong> — {text(image.caption)}"
        if image.credit:
            caption += f' <span class="credit">{text(image.credit)}</span>'
        opened = reopened.get(f"gallery:{gallery.slug}/{image.file}")
        if opened:
            caption += f' <a class="open" href="{attribute(opened)}">{figures.OPEN_TEXT}</a>'
        tiles.append(
            _tile(
                link=relative_href(page, web_res),
                src=relative_href(page, thumb),
                size=image.thumb_size,
                alt=image.alt,
                caption=caption,
            )
        )

    return _shell(
        page=page,
        title=f"{gallery.title} — Making Fractal Wallpapers",
        css=css,
        bar=topbar(article, index_path()),
        rail=sections_module.block(page, sections),
        header=header,
        blocks=["\n".join(intro), _grid(tiles)],
    )


def gallery_index(galleries: list[Gallery], sections: list[sections_module.Section]) -> str:
    """The HTML for the gallery index: one cover tile per gallery.

    With no galleries it is the register standing empty, which is a page the site
    genuinely has: the front page and the site bar both link here, so this has to be
    somewhere a reader can arrive rather than a page that is missing.
    """
    page = GALLERIES_DIR / "index.html"
    css = relative_href(page, SITE_ROOT / "assets" / "css" / "site.css")
    article = relative_href(page, SITE_ROOT / "index.html")

    header = _masthead(None, "Wallpaper packs")

    intro = ['  <section class="intro">']
    if galleries:
        intro.append(
            "    <p>Images on these pages are web-res. Anything a reader would want at "
            "full size is a release download.</p>"
        )
    else:
        # The register with nothing in it. It says what the page is and stops there:
        # a date would be a promise and a count would be a number nobody has, and both
        # are the kind of thing a reader is entitled to hold the page to.
        intro.append(
            "    <p>The finished wallpapers are collected here in packs, to download at "
            "full resolution. Each pack's page shows its pictures at web resolution, and "
            "the full-size files are release downloads.</p>"
        )
    intro.append(f'    <p><a href="{attribute(article)}">Back to the article</a></p>')
    intro.append("  </section>")

    # The page opens on a picture *(favicon_wire_ckpt145)*: every registry figure whose row
    # names this page, derived here exactly as `check` derives it, because a generated page
    # has no hand to paste a block and `pages` holds the whole file to this function.
    name = figures.page_name(page)
    opened = links.opened(page)
    opening = [
        figures.markup(figure, opened)
        for figure in figures.load_all().values()
        if figure.page == name and figure.on_page
    ]
    blocks = [*opening, "\n".join(intro)]
    if galleries:
        tiles = []
        for gallery in galleries:
            cover = gallery.images[0]
            link = f"{gallery.slug}.html"
            caption = (
                f'<strong><a href="{link}">{text(gallery.title)}</a></strong> — '
                f"{text(gallery.blurb)} "
                f'<span class="credit">{_count(len(gallery.images))}</span>'
            )
            tiles.append(
                _tile(
                    link=link,
                    src=relative_href(page, gallery.thumbs_directory / cover.file),
                    size=cover.thumb_size,
                    alt=cover.alt,
                    caption=caption,
                )
            )
        blocks.append(_grid(tiles))

    return _shell(
        page=page,
        title="Wallpaper packs — Making Fractal Wallpapers",
        css=css,
        bar=topbar(article, index_path()),
        rail=sections_module.block(page, sections),
        header=header,
        blocks=blocks,
    )


def library_page(sections: list[sections_module.Section]) -> str:
    """The palette library, every map as a strip, grouped by the colour it is dominant in.

    Generated rather than written because it is nine hundred rows of the same shape, and
    the shape is a record: `check` re-derives it and compares, so a palette that entered
    the record and not the page is a failing check rather than a gap nobody looks at. The
    record is this repository's own — `palettes/library.jsonl`, the way a gallery has its
    `gallery.jsonl` — so the page derives from committed text here and the checkout next
    door is what the *record* is held to, by the `library` check, where there is one.
    """
    page = palettes_module.library_page_path()
    directory = palettes_module.library_assets_dir()
    width, height = palettes_module.LIBRARY_STRIP
    article = relative_href(page, SITE_ROOT / "article" / "color-palettes.html")

    blocks = [
        NEWLINE.join(
            [
                '  <section class="intro">',
                f"    <p>{text(palettes_module.library_lead())}</p>",
                f'    <p><a href="{attribute(article)}">Back to Color palettes</a></p>',
                "  </section>",
            ]
        )
    ]
    for hue, group in palettes_module.held_hues():
        lines = [
            '  <section class="palette-group">',
            # A parenthesis and not an em-dash: the library page is generated, so
            # `builder/dashes.py` cannot sweep it and the rule is held at the two places
            # that write its words, here and `palettes.LIBRARY_LEAD`.
            f'    <h2 id="hue-{hue}">{text(hue.capitalize())} ({len(group)} palettes)</h2>',
            '    <div class="palette-grid">',
        ]
        for held in group:
            lines.extend(_palette_cell(held, page, directory, width, height))
        lines.extend(["    </div>", "  </section>"])
        blocks.append(NEWLINE.join(lines))

    return _shell(
        page=page,
        title=f"{palettes_module.LIBRARY_TITLE} — {SITE_TITLE}",
        css=relative_href(page, SITE_ROOT / "assets" / "css" / "site.css"),
        bar=topbar(
            relative_href(page, SITE_ROOT / "index.html"),
            relative_href(page, GALLERIES_DIR / "index.html"),
        ),
        rail=sections_module.block(page, sections),
        header=_masthead(
            f'<a href="{attribute(article)}">Color palettes</a>', palettes_module.LIBRARY_TITLE
        ),
        blocks=blocks,
    )


def _palette_cell(held, page: Path, directory: Path, width: int, height: int) -> list[str]:
    """One cell of the hue grid: a palette's gradient, what the page calls it, and — where
    those two differ — the id the library actually spells it with.

    The id is on the page rather than in a `title` attribute because it is the key a
    permalink carries and the key a reader searching this page would type, and a tooltip
    is invisible to a touch screen, to a keyboard and to the browser's own find.
    """
    lines = [
        '      <figure class="palette">',
        f"        {_strip(held, page, directory, width, height)}",
        f"        <figcaption>{text(held.display)}</figcaption>",
    ]
    if held.renamed:
        lines.append(f'        <p class="palette-id">{text(held.name)}</p>')
    lines.append("      </figure>")
    return lines


def _strip(held, page: Path, directory: Path, width: int, height: int) -> str:
    """One gradient, at the size the library page draws every one of them."""
    source = relative_href(page, directory / held.strip)
    return (
        f'<img src="{attribute(source)}" width="{width}" height="{height}" '
        f'alt="{attribute(held.alt)}" loading="lazy">'
    )


def generated_pages(galleries: list[Gallery], sections: list[sections_module.Section]) -> dict:
    """Every page the builder owns, as {path: html}. The set `check` compares against.

    The galleries handed in are the **publishable** ones — `galleries.load_all()`, which a
    staged gallery is deliberately not in. A staged record is a record and its pictures
    with no page made from them, so there is nothing for this module to write and nothing
    for the index to carry a cover tile of.
    """
    pages = {GALLERIES_DIR / "index.html": gallery_index(galleries, sections)}
    for gallery in galleries:
        pages[gallery_page_path(gallery)] = gallery_page(gallery, sections)
    pages[palettes_module.library_page_path()] = library_page(sections)
    return pages
